services:
  web:
    build:
      context: .  # The context is still the root directory
      dockerfile: Dockerfile  # Use the Dockerfile located in the root directory
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app/backend  # Bind mount the backend folder to the container
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: "redis:latest"
    container_name: redis-server
    ports:
      - "6379:6379"
